"""Add Ofer's career identity without changing historical article bodies."""
from pathlib import Path
import json,re,html
R=Path(__file__).resolve().parent; BASE='https://ofershap.github.io'; E=html.escape
PROFILE={'@type':'Person','@id':BASE+'/about/#ofer','name':'Ofer Shapira','alternateName':'עופר שפירא','url':BASE+'/about/','jobTitle':'AI Engineering Team Lead','sameAs':['https://github.com/ofershap','https://www.linkedin.com/in/ofershap/'],'knowsAbout':['AI engineering','AI agents','Engineering leadership','Developer tooling','MCP','AI adoption']}
STYLE='''<style>.identity-intro{margin:2rem 0;padding:1.4rem;border:1px solid #ddd;border-radius:8px}.identity-intro p{line-height:1.7}.identity-intro a{display:inline-block;margin-inline-end:1rem;padding:.35rem 0}.identity-topics{padding-inline-start:1.3rem}.identity-topics li{margin:.8rem 0;line-height:1.7}.identity-kicker{font-family:system-ui,sans-serif;color:#555;font-size:.9rem}.identity-note{color:#555;font-size:.9rem}header nav{display:flex;flex-wrap:wrap;gap:.6rem}header nav a{margin:0}header{gap:1rem;align-items:center;flex-wrap:wrap}article p{line-height:1.85}article h2{margin-top:2rem}@media(max-width:500px){main{padding-top:2rem}.identity-intro{padding:1rem}h1{font-size:1.7rem}}</style>'''
HE='''<p class="identity-kicker">AI Engineering · סוכנים · הובלת צוותי פיתוח</p><h1>עופר שפירא</h1><p class="subtitle">בונה מערכות AI. מוביל צוותים שעובדים איתן.</p>
<p>אני עופר שפירא, מוביל צוות AI Engineering ב-Elementor, מפתח ויזם לשעבר. אני עובד בחיבור שבין קוד, מוצר ואנשים: בונה מערכות מבוססות AI, מוביל צוותי הנדסה, ובודק איך סוכנים משנים את העבודה בפועל.</p>
<p>הבלוג הזה הוא הבית של הכתיבה המקצועית שלי. כאן אני מתעד מה בנינו, מה ניסינו, איפה זה נכשל ומה שינינו בעקבות זה. הוא מרכז את הפוסטים שלי מלינקדאין לצד מדריכים ומאמרים, כדי שהידע יישאר נגיש מעבר לפיד.</p>
<h2>במה אני מתמקד</h2><ul class="identity-topics"><li><strong>AI בתוך תהליך הפיתוח:</strong> עבודה עם סוכני קוד, הגדרת משימות, Code Review ובדיקת התוצר.</li><li><strong>סוכנים שמתחברים למערכות אמיתיות:</strong> כלים, MCP, אוטומציה וניהול הקשר.</li><li><strong>הובלת צוותי הנדסה:</strong> אימוץ AI בצוות, אחריות על החלטות והמעבר מכתיבת קוד לבדיקתו.</li><li><strong>כלי פיתוח וקוד פתוח:</strong> כלים קטנים שמקצרים עבודה חוזרת ומאפשרים לבדוק רעיון בפועל.</li></ul>
<h2>הרקע שלי</h2><p>יש לי יותר מ-15 שנות ניסיון בפיתוח ובהובלת צוותים. לפני Elementor עבדתי ב-monday.com, הובלתי צוותי פיתוח ב-Via וב-Novidea, וייסדתי את DSM Tool, חברת SaaS שנרכשה בהמשך בידי AutoDS. אני בעל תואר ראשון במדעי המחשב ותואר MBA, ובוגר יחידה 8200 כמפתח תוכנה.</p><p>הניסיון הזה משפיע על השאלות שאני שואל: האם המערכת פותרת בעיה אמיתית, איך היא משתלבת בעבודה של הצוות, ואיך יודעים שהיא עובדת גם אחרי הדמו.</p>
<h2>פרויקטים פתוחים</h2><ul class="identity-topics"><li><a href="https://github.com/ofershap/real-browser-mcp">real-browser-mcp</a> - חיבור סוכנים לדפדפן Chrome אמיתי עם ההתחברויות הקיימות.</li><li><a href="https://github.com/ofershap/agents-control-tower">agents-control-tower</a> - הפעלה ומעקב אחר סוכני Cursor מהטרמינל.</li><li><a href="https://github.com/ofershap/cursor-usage-tracker">cursor-usage-tracker</a> - מעקב שימוש ועלות של Cursor בצוות.</li></ul>
<h2>מאיפה להתחיל לקרוא</h2><ul class="identity-topics"><li><a href="/posts/linkedin-7497163554815381504/">איך מקלים על Code Review בעזרת PR Description</a> - ארבעה חלקים שעוזרים להבין שינוי לפני קריאת הקוד.</li><li><a href="/posts/linkedin-7495353124623278080/">איך מסנכרנים משתני סביבה בצוות</a> - מעבר מתיאום ידני לפעולה שמתרחשת בזמן הרצה.</li><li><a href="/posts/linkedin-7502999614728519681/">מי דואג שקבצי הקונטקסט נשארים נכונים</a> - ההבדל בין זיהוי קישור שבור לבין בעיה שצריך לתקן.</li></ul>
<h2>קשר ופרופילים</h2><p><a href="https://www.linkedin.com/in/ofershap/">LinkedIn - כתיבה וקשר מקצועי</a><br><a href="https://github.com/ofershap">GitHub - הפרויקטים והקוד</a></p><p class="identity-note">הכתיבה כאן היא אישית. פוסטים היסטוריים משקפים את המועד שבו נכתבו; קישור למקור מופיע בכל פוסט מיובא.</p>'''
EN='''<p class="identity-kicker">AI engineering · Agents · Engineering leadership</p><h1>Ofer Shapira</h1><p class="subtitle">Building AI systems. Leading the teams that use them.</p>
<p>I am Ofer Shapira, an AI Engineering Team Lead at Elementor, a developer and a former SaaS founder. My work sits between software, product and people: building AI systems, leading engineering teams and testing how agents change day-to-day work.</p><p>This blog is my professional writing home. I document what we built, what we tried, what failed and what we changed. It brings together my LinkedIn posts, guides and essays so the work stays useful beyond the feed.</p>
<h2>What I focus on</h2><ul class="identity-topics"><li><strong>AI in software delivery:</strong> coding agents, task definition, code review and checking the result.</li><li><strong>Agents connected to real systems:</strong> tools, MCP, automation and context management.</li><li><strong>Engineering leadership:</strong> AI adoption, responsibility for decisions and the shift from writing code to judging it.</li><li><strong>Developer tools and open source:</strong> focused tools that remove repetitive work and make ideas testable.</li></ul>
<h2>Background</h2><p>I have more than 15 years of software engineering and leadership experience. Before Elementor, I worked at monday.com, led engineering teams at Via and Novidea, and founded DSM Tool, a SaaS business later acquired by AutoDS. I hold a B.Sc. in Computer Science and an MBA, and served as a software developer in Unit 8200.</p><p>That background shapes the questions I ask: does the system solve a real problem, how does it fit the team's work, and how do we know it works after the demo?</p>
<h2>Open projects</h2><ul class="identity-topics"><li><a href="https://github.com/ofershap/real-browser-mcp">real-browser-mcp</a> - connect agents to a real Chrome session with existing logins.</li><li><a href="https://github.com/ofershap/agents-control-tower">agents-control-tower</a> - launch and monitor Cursor agents from the terminal.</li><li><a href="https://github.com/ofershap/cursor-usage-tracker">cursor-usage-tracker</a> - track a team's Cursor usage and cost.</li></ul>
<h2>Start reading</h2><p>These first-hand examples are in Hebrew; the archive also includes selected translations.</p><ul class="identity-topics"><li><a href="/posts/linkedin-7497163554815381504/">Make code review easier with a PR description</a> - four parts that help explain a change before reading its code.</li><li><a href="/posts/linkedin-7495353124623278080/">Keep a team's environment variables in sync</a> - replace manual coordination with a step at application startup.</li><li><a href="/posts/linkedin-7502999614728519681/">Keep agent context files accurate</a> - distinguish a broken reference from a problem worth fixing.</li></ul>
<h2>Contact and profiles</h2><p><a href="https://www.linkedin.com/in/ofershap/">LinkedIn - writing and professional contact</a><br><a href="https://github.com/ofershap">GitHub - projects and code</a></p><p class="identity-note">This is my personal writing. Historical posts reflect when they were written; imported posts link to their original source.</p>'''
def build():
 for lang,body,path,title in [('he',HE,'about','עופר שפירא | AI Engineering והובלת צוותים'),('en',EN,'about/en','Ofer Shapira | Practical AI engineering leadership')]:
  d=R/path;d.mkdir(parents=True,exist_ok=True);url=BASE+'/'+path+'/'
  schema={'@context':'https://schema.org','@type':'ProfilePage','url':url,'mainEntity':PROFILE}
  desc='עופר שפירא: מוביל AI Engineering, מפתח ויזם. סוכנים, כלי פיתוח והובלת צוותים מתוך ניסיון מעשי.' if lang=='he' else 'Ofer Shapira: AI engineering leader, developer and former SaaS founder. First-hand writing on agents, developer tools and engineering leadership.'
  nav='<a href="/">כתיבה</a><a href="/about/en/">English</a>' if lang=='he' else '<a href="/">Writing</a><a href="/about/">עברית</a>'
  page=f'<!doctype html><html lang="{lang}" dir="'+('rtl' if lang=='he' else 'ltr')+f'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{E(title)}</title><meta name="description" content="{E(desc)}"><link rel="canonical" href="{url}"><link rel="alternate" hreflang="he" href="{BASE}/about/"><link rel="alternate" hreflang="en" href="{BASE}/about/en/"><link rel="alternate" hreflang="x-default" href="{BASE}/about/en/"><link rel="stylesheet" href="/style.css">{STYLE}<meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(desc)}"><meta property="og:url" content="{url}"><meta property="og:type" content="profile"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><header><span class="site-name"><a href="/">Ofer Shapira</a></span><nav>{nav}</nav></header><main><article>{body}</article><footer><a href="/">'+('כל הכתיבה' if lang=='he' else 'All writing')+'</a> · <a href="/feed.xml">RSS</a></footer></main></body></html>'
  (d/'index.html').write_text(page)
 p=R/'index.html';s=p.read_text();s=re.sub(r'<section class="identity-intro".*?</section>','',s,flags=re.S)
 intro='<section class="identity-intro" aria-label="About Ofer Shapira"><p class="identity-kicker">Practical AI engineering leadership</p><p>I’m Ofer Shapira, an AI Engineering Team Lead at Elementor, a developer and a former SaaS founder. I write about building AI systems, leading engineering teams and turning agent experiments into ways of working.</p><a href="/about/">עליי בעברית</a><a href="/about/en/">About &amp; selected work</a></section>'
 s=s.replace('<section class="archive-intro"',intro+'<section class="archive-intro"',1);s=s.replace('</head>',STYLE+'</head>') if '.identity-intro{' not in s else s
 def schema_patch(m):
  j=json.loads(m[1])
  if j.get('@type')=='WebSite':j['author']=PROFILE;j['publisher']=PROFILE
  return '<script type="application/ld+json">'+json.dumps(j,ensure_ascii=False)+'</script>'
 s=re.sub(r'<script type="application/ld\+json">(.*?)</script>',schema_patch,s,flags=re.S);p.write_text(s)
 p=R/'for-ai/index.html';s=p.read_text();s=re.sub(r'<section class="identity-links".*?</section>','',s,flags=re.S);s=s.replace('</article>','<section class="identity-links"><h2>Professional identity</h2><p>Ofer writes about practical AI engineering leadership: building AI systems, leading engineering teams and making agent workflows useful in real work.</p><p><a href="/about/">Full professional bio in Hebrew</a> · <a href="/about/en/">English professional bio and selected work</a></p></section></article>');s=re.sub(r'"mainEntity":\s*\{.*?\}\}',lambda m:'"mainEntity":'+json.dumps(PROFILE,ensure_ascii=False)+'}',s);p.write_text(s)
 p=R/'llms.txt';s=p.read_text();s=re.sub(r'\n## Professional identity.*?(?=\n## |\Z)','',s,flags=re.S)
 block='\n## Professional identity\n\n- [Ofer Shapira: Hebrew bio and selected work]('+BASE+'/about/)\n- [Ofer Shapira: English bio and selected work]('+BASE+'/about/en/)\n\nPositioning: practical AI engineering leadership. This is Ofer’s personal professional writing home, independent of any agency service offering.\n'
 if '\n## Original service Q&A' in s:s=s.replace('\n## Original service Q&A',block+'\n## Original service Q&A')
 else:s+=block
 p.write_text(s)
 p=R/'sitemap.xml';s=p.read_text()
 for path in ['about','about/en']:
  u='<url><loc>'+BASE+'/'+path+'/</loc></url>'
  if u not in s:s=s.replace('</urlset>',u+'</urlset>')
 p.write_text(s)
if __name__=='__main__':build()
